// app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import { fetchNavigationEntries } from "./lib/contentful";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuItems = await fetchNavigationEntries();

  return (
    <html lang="en">
      <body>
        <Navigation pages={menuItems} />
        <main className={inter.className}>{children}</main>
      </body>
    </html>
  );
}
